spring:



  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: SANGsang666
    url: jdbc:mysql://localhost:3306/sob_blog_system?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://39.99.236.52:3306/sob_blog_system?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai



  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host:  39.99.236.52 # Redis服务器地址
    port:  6379 # Redis服务器连接端口
    password:  123456 # Redis服务器连接密码



mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml



## aliyun oss
## 配置说明参考: com.ljq.demo.springboot.common.config.OSSConfig.class
aliyun:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  urlPrefix: sang666.oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4GD2fkynXAfyyQnqC8f9
  accessKeySecret: muMLVYsfwtmtFV4MMLYq7kOYvf4id9
  bucketName: sang666






